all:
  hosts:
    node1:
      ansible_host: 192.168.2.100
      ip: 192.168.2.100
      access_ip: 192.168.2.100
    node2:
      ansible_host: 192.168.2.101
      ip: 192.168.2.101
      access_ip: 192.168.2.101
    node3:
      ansible_host: 192.168.2.102
      ip: 192.168.2.102
      access_ip: 192.168.2.102
  children:
    kube-master:
      hosts:
        node1:
        node2:
        node3:
    kube-node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
